### ISSUE TITLE
Can't search

### ISSUE THREAD

**Issue by gnl221** [cbernhard21/ICT-4510-project-3#1]
This thing doesn't have a search feature. I refuse to use it until then. lol

**Comment by cbernhard21** [comment]
Haha!  Eventually it will.  Gotta find a good API for city and zip code search.  Just trying to figure out Leaflet.js first

**Comment by cbernhard21** [comment]
Haha!  Eventually it will.  Gotta find a good API for city and zip code search.  Just trying to figure out Leaflet.js first
